### ISSUE TITLE
cog mediatype at iana

### ISSUE THREAD

**Issue by pvgenuchten** [cogeotiff/cog-spec#13]
Has there been any discussion on the use of a dedicated mediatype for COG?

Does it make sense to have a dedicated mediatype, or is it better to tag COG files as regular image/tiff files?

If relevant, are there initiatives to register the cog mediatype at [iana](https://www.iana.org/assignments/media-types/media-types.xhtml)? 

Question comes from the catalogue world, which wants to reference COG files from metadata records indicating the proper mediatype.

**Comment by vincentsarago** [comment]
It should be `image/tiff; application=geotiff; profile=cloud-optimized`

Not sure where it comes from exactly but this has been discussed quite some time ago. FYI it's the one used in STAC https://github.com/stac-utils/pystac/blob/main/pystac/media_type.py#L7

I'm not sure if this was ever registered to Iana. maybe @cholmes knows

**Comment by pvgenuchten** [comment]
Thanx @vincentsarago, doesit make sense to add this aspect to the specification document?

**Comment by vincentsarago** [comment]
would be a nice addition yes

**Comment by rouault** [comment]
I would point this discussion is redundant with https://github.com/opengeospatial/CloudOptimizedGeoTIFF/issues/1 and should maybe be closed in favor of it. The addition of new keys is apparently a no-go for IANA since you can only use keys that were foreseen in the image/tiff registration, but profile might be a special case due to another spec.

**Comment by pvgenuchten** [comment]
While reading those threads; my impression is that:
- the tiff mediatype as defined at iana does not allow to add alternative parameters then `application`, so the convention to use profile=cloud-optized is not correct
- [suggestion by @EmDevys](https://github.com/opengeospatial/CloudOptimizedGeoTIFF/issues/1#issuecomment-987271816) to replace `application=geotiff; profile=cloud-optimized` for  `application=geotiff+cog` makes sense
- using a dedicated parameter to differentiate geotiff from tiff can not be registered as such at iana (use of the application parameter is implicit to the image/tiff definition)

+1 to close this issue, and continue on the remote thread
