### ISSUE TITLE
Are overviews optional ? 

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/cog-spec#2]
The specification is not 💯 clear about the overview being optional or not, while `validate_cloud_optimized_geotiff.py` script make them mandatory if the file is more than 512x512px. 
https://github.com/OSGeo/gdal/blob/c548ad24c9a39b9492e18cf41ed8d44d69f40b57/gdal/swig/python/samples/validate_cloud_optimized_geotiff.py#L89-L98

IMO it make senses that overviews are needed for file that are > 512x512px so we can visualize them with few range request. 
If they are optional then the script will need to be updated.

cc @cholmes @rouault @normanb

**Comment by normanb** [comment]
Noting that the current draft of the spec says this about overviews 

`Optional: IFD (Image File Directory) of first overview (typically subsampled by a factor of 2), followed by the values of its tags that don't fit inline`

I have created https://github.com/OSGeo/gdal/pull/1023 to correct the validate_cloud_optimized_geotiff.py script and change this error to a warning and to reflect the spec.

**Comment by normanb** [comment]
https://github.com/OSGeo/gdal/pull/1023 was merged. Closing this issue.
